version: '3.8'

services:
  # Strapi CMS Backend - Internal network only
  strapi:
    build:
      context: .
      dockerfile: apps/strapi/Dockerfile
      args:
        APP: strapi
        WORKSPACE: '@repo/strapi'
    restart: unless-stopped
    env_file: .env # 🎯 Automatically loads ALL environment variables
    environment:
      # Override specific values for production
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_SSL: true
      DATABASE_SSL_REJECT_UNAUTHORIZED: false
    ports:
      - '127.0.0.1:1337:1337' # Only bind to localhost
    volumes:
      - strapi_uploads:/app/apps/strapi/public/uploads
    networks:
      - cabernai_network
      - default # Connect to default network for external nginx access
    labels:
      - 'traefik.enable=false'

  # Next.js Frontend - Internal network only
  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
      args:
        APP: ui
        WORKSPACE: '@repo/ui'
    restart: unless-stopped
    env_file: .env # 🎯 Automatically loads ALL environment variables
    environment:
      # Override specific values for production
      NODE_ENV: production
    ports:
      - '127.0.0.1:3000:3000' # Only bind to localhost
    networks:
      - cabernai_network
      - default # Connect to default network for external nginx access
    depends_on:
      - strapi
    labels:
      - 'traefik.enable=false'

  # Watchtower for automatic updates (optional)
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
      WATCHTOWER_INCLUDE_STOPPED: true
    command: --interval 3600 --cleanup --scope cabernai-web
    networks:
      - cabernai_network
    labels:
      - 'com.centurylinklabs.watchtower.scope=cabernai-web'

volumes:
  strapi_uploads:
    name: cabernai_strapi_uploads

networks:
  cabernai_network:
    name: cabernai_network
    driver: bridge
